# Site settings
baseURL = "http://fusecure.github.io/"
languageCode = "en-us"
title = "FUSECURE"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-137356245-2"

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "GodFix"
  description = "Software Solutions"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Fusecure"
    subtitle = "By GodFix"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    # [[params.navigation.links]]
    #   name = "Home"
    #   url = "#"

    # [[params.navigation.links]]
    #   name = "Features"
    #   url = "blogs"

    # [[params.navigation.links]]
    #  name = "Generic Blog"
    #  url = "blogs/ipsum"

    # [[params.navigation.links]]
    #   name = "Elements"
    #   url = "elements.html"

    # [[params.navigation.links]]
    #   name = "Contact"
    #   url = "#contact"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "#"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Secure Data Sharing"
    subtitle = "KEEP PASSWORDS, FINANCIAL INFORMATION AND IDENTITY SECURE ON YOUR LOCAL MACHINE OR OUR SAAS PLATFORM"
    buttonText = "FEATURES"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Data encryption"
      subtitle = "We protect digital data confidentiality"
      image = "pic01.jpg"
      url = "blogs/aliquam"

    [[params.tiles.showcase]]
      title = "Separate levels of accessibility"
      subtitle = "Depending on the accessibility permissions it is possible to share specific data with specific people"
      image = "pic02.jpg"
      url = "blogs/tempus"

    [[params.tiles.showcase]]
      title = "Multi-factor authentication"
      subtitle = "Person is granted access only after successfully presenting several pieces of evidence to an authentication mechanism: USB stick with a secret token, password, PIN, biometrics, voice, typing speed, pattern in key press intervals, etc."
      image = "pic03.jpg"
      url = "blogs/magna"

    [[params.tiles.showcase]]
      title = "Analytics"
      subtitle = "We provide history logs and report suspicious activities"
      image = "pic04.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Top secure"
      subtitle = "We provide a software packages in order to install FUSECURE on your local machine and increase security due operating only in your local network"
      image = "pic05.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Fully-customized"
      subtitle = "The end result is a well customized system optimized for your business needs"
      image = "pic06.jpg"
      url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Don't share passwords and confidential information via messengers!"
    subtitle = """Use our software."""
    buttonText = "Learn more"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "godfixsoft@gmail.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "godfixsoft@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+38 (098) 575-4354"

    [[params.contact.address]]
    title = "Team Location"
    # street = "Street"
    city = "Zaporozhye"
    country = "Ukraine"

  # Footer section
  [params.footer]
    enable = true
    copyright = "GodFix Software"

    # Uses font awesome icons
    # [[params.footer.social]]
    #   icon = "fa-twitter"
    #   url= "https://www.twitter.com"
    #   label = "Twitter"

    # [[params.footer.social]]
    #   icon = "fa-facebook"
    #   url= "https://www.facebook.com"
    #   label = "Facebook"

    # [[params.footer.social]]
    #   icon = "fa-instagram"
    #   url= "https://www.instagram.com"
    #   label = "Instagram"
    
    # [[params.footer.social]]
    #   icon = "fa-github"
    #   url= "https://www.github.com"
    #   label = "GitHub"

    # [[params.footer.social]]
    #   icon = "fa-linkedin"
    #   url= "https://www.linkedin.com"
    #   label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Company Website: "
      url= "https://godfix.github.io"
      alt = "GodFix"
